---
- name: Playbook to reboot Windows servers
  hosts: all
  gather_facts: true
  tasks: 
  - name: Rebooting Windows servers
    win_reboot:
      pre_reboot_delay: 2 
      reboot_timeout: 600
      msg: "Reboot initiated by Ansible Tower"
